apps/producto/urls.py
from django.conf.urls import url
from views import index, comprar, productos, viewCategorias, nuevoRegistro, editarRegistro, eliminarRegistro, nuevaCategoria, editarCategoria, eliminarCategoria

app_name = 'productos'
urlpatterns=[
    url(r'^index/$', index),
    url(r'^index/comprar/$', comprar),
    url(r'^categorias/$', viewCategorias.as_view(), name='categorias'),
    url(r'^productos/$', productos, name='productos'),
    url(r'^productos/nuevoRegistro/$', nuevoRegistro, name='nuevoRegistro'),
    url(r'^productos/editarRegistro/(?P<idProducto>\d+)$', editarRegistro, name='editarRegistro'),
    url(r'^productos/eliminarRegistro/(?P<idProducto>\d+)$', eliminarRegistro, name='eliminarRegistro'),
    url(r'^categorias/nuevaCategoria/$', nuevaCategoria, name='nuevaCategoria'),
    url(r'^categorias/editarCategoria/(?P<idCategoria>\d+)$', editarCategoria, name='editarCategoria'),
    url(r'^categorias/eliminarCategoria/(?P<idCategoria>\d+)$', eliminarCategoria, name='eliminarCategoria'),
]

tienda/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps import producto

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'producto/', include('apps.producto.urls', namespace = 'producto')),
]

apps/producto/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class categoria(models.Model):
    nombre = models.CharField(max_length=30)
    f_creacion = models.DateField()
class producto(models.Model):
    nombreProducto = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=150)
    costo = models.DecimalField(max_digits=6, decimal_places=2)
    disponible = models.BooleanField()
    n_existencias = models.IntegerField()
    categoria = models.ForeignKey('categoria')

apps/producto/forms.py
from django import forms
from models import producto, categoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = categoria
        fields = [
        'nombre',
        'f_creacion'
        ]
        labels = {
        'nombre' : 'nombre',
        'f_creacion' : 'f_creacion',
        }
        widgets = {
        'nombre' : forms.TextInput(attrs={'class' : 'form-control'}),
        'creacion' : forms.TextInput(attrs={'class' : 'form-control'}),
        }

class ProductoForm(forms.ModelForm):
    class Meta:
        model = producto
        fields = [
        'nombreProducto',
        'descripcion',
        'costo',
        'disponible',
        'n_existencias',
        'categoria',
        ]
        labels = {
        'nombreProducto' : 'Producto',
        'descripcion' : 'descripcion',
        'costo' : 'costo',
        'disponible' : 'disponible',
        'n_existencias' : 'existencias',
        'categoria' : 'categoria',
        }
        widgets = {
        'Producto' : forms.TextInput(attrs={'class' : 'form-control'}),
        'descripcion' : forms.TextInput(attrs={'class' : 'form-control'}),
        'costo' : forms.TextInput(attrs={'class' : 'form-control'}),
        'disponible' : forms.TextInput(attrs={'class' : 'form-control'}),
        'existencias' : forms.TextInput(attrs={'class' : 'form-control'}),
        'categoria' : forms.TextInput(attrs={'class' : 'form-control'}),
        }

apps/producto/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import HttpResponse
from models import producto, categoria
from django.views.generic import ListView
from forms import *
import json
import models

def index(request):
    contexto = {
        'productos' : producto.objects.all(),
        'categorias' : categoria.objects.all()
    }
    return render(request,'base/index.html',contexto)

def comprar(request):
        data = request.GET.get("data")
        dat = json.loads(data)
        for dato in dat:
            id = dato[0]
            cantidad = dato[1]
            producto = models.producto.objects.filter(id=id).first()
            total = int(producto.n_existencias)
            val = (producto.n_existencias - cantidad)
            producto.n_existencias = val
            producto.save()
        valor = "listo"
	return HttpResponse(valor)

# def categorias(request):
# 	contexto = {
# 		'categorias': categoria.objects.all()
# 	}
# 	return render(request, 'producto/categorias.html', contexto)

def productos(request):
    contexto = {
    	'productos': producto.objects.all()
    }
    return render(request, 'producto/productos.html', contexto)

class viewCategorias(ListView):
	model = categoria
	template_name = 'producto/categorias.html'
	queryset = categoria.objects.all()

def nuevoRegistro(request):
	if request.method == 'POST':
		form = ProductoForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('producto:productos')
	else:
		form = ProductoForm()
	return render(request, 'producto/productoFormulario.html', {'form' : form})

def editarRegistro(request, idProducto):
	productoid = producto.objects.get(id=idProducto)
	if request.method == 'GET':
		form = ProductoForm(instance = productoid)
	else:
		form = ProductoForm(request.POST, instance=productoid)
		if form.is_valid():
			form.save()
		return redirect('producto:productos')
	return render(request, 'producto/productoFormulario.html', {'form' : form})

def eliminarRegistro(request, idProducto):
	productoid = producto.objects.get(id=idProducto).delete()
	return redirect('producto:productos')

def nuevaCategoria(request):
	if request.method == 'POST':
		form = CategoriaForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('producto:categorias')
	else:
		form = CategoriaForm()
	return render(request, 'producto/categoriaFormulario.html', {'form' : form})

def editarCategoria(request, idCategoria):
	categoriaid = categoria.objects.get(id=idCategoria)
	if request.method == 'GET':
		form = CategoriaForm(instance = categoriaid)
	else:
		form = CategoriaForm(request.POST, instance=categoriaid)
		if form.is_valid():
			form.save()
		return redirect('producto:categorias')
	return render(request, 'producto/categoriaFormulario.html', {'form' : form})

def eliminarCategoria(request, idCategoria):
	categoriaid = categoria.objects.get(id=idCategoria).delete()
	return redirect('producto:categorias')

templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Estilos para todas las paginas que hereden de esta plantilla -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

    <!-- Bloque para incrustar otros css diferentes por pagina -->
    {% block extracss %}<link rel="stylesheet" type="text/css" href="{% static 'css2/basic_style.css' %}">{% endblock %}
    <title>{% block title %}Libreria Sempere e Hijos{% endblock %}</title>
  </head>

  <body onload="cargar();">
    <header>
      {% block header %}
        {% include 'base/nav.html' %}
      {% endblock %}
    </header>
    {% block content %}

    <div class="center">
      <!-- <div class="vista"> -->
        {% for categoria in categorias %}

          <div class="conjunto">
            <div class="categoria">
              {{ categoria.nombre }}
            </div>
            <div class="libro">
              {% for producto in productos %}
                {% if producto.categoria_id == categoria.id %}
                  {% if producto.n_existencias != 0 %}

                    <div class="unidad" id='{{producto.id}}'>
                      <i class="fa fa-book" aria-hidden="true"></i>
                      <span class="titulo"> {{ producto.nombreProducto }} </span>
                      <span class="autor"> {{ producto.descripcion }} </span>
                      <span class="costo" > $ <span id='costo{{producto.id}}' class="cos">{{ producto.costo }}</span></span>
                      <span class="costo">En existencia: {{producto.n_existencias}}</span>
                      <input type="number" class="number" id="numero{{producto.id}}" max='{{producto.n_existencias}}' min="0" value="0" onchange="sumar({{producto.id}});" >
                    </div>
                  {% endif %}
                {% endif%}
              {% endfor %}
            </div>
          </div>
        {% endfor%}
      <button class="comprar" type="button" name="button" onclick="realizarCompra();"> COMPRAR </button>
    </div>
    <div class="center" id="cen">
      <div class="modal">
        <span id="T">Realizar compra</span>
        <span>Articulos comprados:</span>
        <span id="articulos"></span>
        <span>Total:</span>
        <span id="total">$</span>
        <button type="button" class="compra" name="button" onclick="comprar();">Comprar</button>

      </div>
    </div>
    {% endblock %}
  </body>
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/funciones.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
</html>

templates/base/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark head">
  <a class="navbar-brand" href="/producto/index">Libreria Sempere e Hijos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/producto/productos">productos<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/producto/categorias">Categorias</a>
      </li>
    </ul>
  </div>
</nav>

templates/informacionAdicional.html
{% extends 'base/index.html' %}
{% loadstaticfiles %}
{% block content %}
<div class="container">
  <a href="{% url 'producto:plantilla' %}" class="btn-mb3">
  Nuevo registro</a>
</div>
{% endblock %}

templates/producto/categoriaFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}
{% block extracss %}
{% endblock %}
{% block content %}
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8">
			<h1>Registro de nueva categoria</h1>
      <form method="post">
        {% csrf_token %}
		  	{{ form.as_p }}
		  	<button type="submit" class="btn btn-success">Enviar</button>
		  	</form>
	  	</div>
  	</div>
</div>
{% endblock %}

templates/producto/categorias.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block content %}
  <div class="info">
    <table class="table table-dark text-center">
      <tr id="titulo">
        <th scope="col">categoria</th>
        <th scope="col">fecha de registro</th>
        <th scope="col">acciones</th>
      </tr>
    {% for categoria in object_list %}
      <tr id="cuerpo">
        <th scope="col">
          <p>{{categoria.nombre}}</p>
        </th>
        <th scope="col">
          <p>{{categoria.f_creacion}}</p>
        </th>
        <th>
          <a href="{% url 'producto:editarCategoria' idCategoria=categoria.id %}" class="btn mb-3">Editar</a>
          <a href="{% url 'producto:eliminarCategoria' idCategoria=categoria.id %}" class="btn mb-3">Borrar</a>
        </th>
      </tr>
    {% empty %}
    	<p>No hay categorias</p>
    {% endfor %}
  </table>
    <a href="{% url 'producto:nuevaCategoria' %}"class="btn btn-primary">Nuevo Registro</a>
  </div>
{% endblock %}

templates/producto/productoFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
{% endblock %}
{% block content %}
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8">
			<h1>Registro de nuevo producto</h1>
      <form method="post">
        {% csrf_token %}
		  	{{ form.as_p }}
		  	<button type="submit" class="btn btn-success">Enviar</button>
		  	</form>
	  	</div>
  	</div>
</div>
{% endblock %}

templates/producto/productos.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block content %}
  <div class="info">
    <table class="table table-dark text-center">
      <tr id="titulo">
        <th class="linea">Producto</th>
        <th class="linea">autor</th>
        <th class="linea">Costo</th>
        <th class="linea">Disponible</th>
        <th class="linea">Existencias</th>
        <th scope = col">acciones</th>
      </tr>
    {% for producto in productos %}
      <tr id="cuerpo">
        <th class="linea">
          <p>{{producto.nombreProducto}}</p>
        </th>
        <th class="linea">
          <p>{{producto.descripcion}}</p>
        </th>
        <th class="linea">
          <p>{{producto.costo}}</p>
        </th>
        <th class="linea">
          {% if producto.disponible %}
          <p>Si</p>
          {% else %}
          <p>No</p>
          {% endif %}
        </th>
        <th class="linea">
          <p>{{producto.n_existencias}}</p>
        </th>
        <th>
          <a href="{% url 'producto:editarRegistro' idProducto=producto.id %}" class="btn mb-3">Editar</a>
          <a href="{% url 'producto:eliminarRegistro' idProducto=producto.id %}" class="btn mb-3">Borrar</a>
        </th>
      </tr>

    {% empty %}
    	<p>No hay productos</p>
    {% endfor %}
  </table>
  <a href="{% url 'producto:nuevoRegistro' %}"class="btn btn-primary">Nuevo Registro</a>
  </div>

{% endblock %}
  <!-- {% block links %}
    <li class="breadcrumb-item"><a href="{% url 'producto:categorias' %}">Categorias</a></li>
    <li class="breadcrumb-item active" aria-current="page">Productos</li>
  {% endblock %} -->